### ISSUE TITLE
Content Enhancement: Top Topics that Need Better Documentation

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/docs#239]
We get a constant stream of questions about certain topics -- in emails, Github Issues, conversations on IRC, face-to-face exchanges, etc.  This is a sign that we need to do a better job of documenting these topics, putting answers in the places where people will find them, and providing ways to follow ongoing work in these areas.

## Topics to Document

We should check each of these off **when the volume of queries about the topic drops near zero**, which will be a sign that either people are finding answers elsewhere or the topic is no longer important. 

- [ ] **Deleting Content You've Added to IPFS** -- especially Right to Be Forgotten - see ipfs/blog#112
- [ ] **Private Content** -- limiting who can read/decrypt the stuff you've published on the IPFS network - see ipfs/blog#115
- [ ] **Private Networks** -- limiting which nodes/peers you will even talk to. This limits which peers can see what you've added to your IPFS node and limits which nodes you will provide blocks to - see ipfs/blog#114
- [ ] **Making content Persist on the Network** -- How to get the content to stay on the IPFS network after your machine disconnects - see ipfs/blog#113

If you can think of any other under-documented topics, please say so in the comments on this issue.

## Things we can Do to Address This

Some things we must to in order to reduce the volume of queries:
* Establish clear documentation to address the topic 
* Publish links to that documentation places where people are looking
* **Provide inroads for people to engage in, or follow, ongoing design/development efforts**
* Gather ideas from the community about other ways to answer these questions or other channels for broadcasting the answers

**Comment by jessicaschilling** [comment]
These topics are being addressed in a variety of other open issues in docs repo -- closing as a result.
