### ISSUE TITLE
Docs that need review

### ISSUE THREAD

**Issue by lgierth** [ipfs/docs#32]
Just so we don't lose track of stuff (I am already). Please post new stuff as you open PRs.

- [ ] multiformats/go-multistream#15 -- Fix and improve example. Add Gx instructions. Golint.
- [x] multiformats/go-multihash#50 -- improve example, link to godoc, make golint happy
- [ ] libp2p/go-libp2p#186 -- go-libp2p documentation effort
- [ ] libp2p/go-libp2p#185 -- Libp2p examples
- [ ] ipfs/js-ipfs#791 -- Tutorial: transfer-files
- [ ] ipfs/website#171 -- Add instructions on how to use ipfs-update and how to upgrade
- [ ] ipfs/fs-repo-migrations#59 -- Update README and run.md guide
- [ ] libp2p/specs#10 -- Add inital PNet spec

**Comment by hsanjuan** [comment]
For every PR I reference the libp2p docs issue, so this is double work for me. I'm keeping track already in that issue (and you can see what is open/merged)

**Comment by lgierth** [comment]
Oh yeah fair! :+1:
