### ISSUE TITLE
GitHub Hygiene: Develop a standard way to indicate a repo/project is deprecated

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#54]
Developers who are building things on top of IPFS have pretty much all indicated that they’ve solved a lot of their problems by digging through IPFS source code and through the repos here on GitHub. Unfortunately, [a huge proportion of repos there are deprecated, but not clearly marked as such](https://docs.google.com/spreadsheets/d/1IDVAGfniyHCJLIxLc3y7K7YTOFGCtgwTVCZEojtNLlw) (gray, red, and possibly many of the orange lines in that spreadsheet), making that job much harder.

We won’t suddenly have perfect docs that solve all of their problems tomorrow, so we should coming up with a standard way of marking out deprecated repos that we can easily and quickly apply:

- Have a standard indicator/text in the repo description
- Have a standard indicator/text at the start of the readme
- Think about a policy for when/how to *archive* repos (makes them read-only and hides them from most listings)
- Apply it to all repos that should be deprecated.
- Also think about the same things for repos that are “in hibernation.” (And should any of those be deprecated instead?)

I’d suggest:

- Description always starts with “DEPRECATED:”
- Readme title always starts with “DEPRECATED:”
- Immediately below the readme title there should be a bold or italicized paragraph about:
    - Why it was deprecated
    - When it was deprecated
    - Where to go for the same resource/functionality/whatever now (if applicable)

---

(Edit: surfacing our final decisions here so they are easy to find)

# Conclusions/Final Process

- Add the topic `deprecated` to the repo (pulling this over from #57)
- Prefix the repo’s description with “DEPRECATED:”
- Prefix the README title with “DEPRECATED:” (If a repo does not have a readme or its readme is empty, add one with the title: “DEPRECATED: [repo name]”
- Follow the README title with a paragraph describing:
    - Why it was deprecated
    - When it was deprecated
    - Where to go for the same resource/functionality/whatever now (if applicable)
- Finally, if a repo is *dead*, archive it (but don’t *delete* it). A *dead* repo might be [`ipfs.js`](https://github.com/ipfs/ipfs.js), while a non-dead, non-archived one might be [`newsletter`](https://github.com/ipfs/newsletter), where we might bring it back in the future.
    - Why archive? links still work, but this hides it from most views and lists on GitHub, *drastically* reducing noise and confusion. For repos like [`support`](https://github.com/ipfs/support/issues), this also prevents people from posting new issues.
    - Downsides: issues and discussions get frozen. We may want to preserve that functionality on some repos (e.g. ones that are freshly deprecated or that haven’t gained any traction/that we can’t support, but that we might want to revisit later).

## Checklist of Repos to Fix

**Definitely deprecated repos:**

- [ ] https://github.com/ipfs/starlog
- [ ] https://github.com/ipfs/examples
- [x] https://github.com/ipfs/faq
- [ ] https://github.com/ipfs/http-api-spec
- [ ] https://github.com/ipfs/go-blocks
- [ ] https://github.com/ipfs/go-commands
- [ ] https://github.com/ipfs/js-ipfs-merkle-dag
- [x] https://github.com/ipfs/support
- [ ] https://github.com/ipfs/newsletter
- [ ] https://github.com/ipfs/datatogether
- [x] https://github.com/ipfs/ipfs-mans Issue: https://github.com/ipfs/ipfs-mans/issues/1#issuecomment-413627930
- [ ] https://github.com/ipfs/dnslink-deploy Dead according to @VictorBjelkholm
- [ ] https://github.com/ipfs/go-sbs (I confirmed this is deprecated with @Kubuxu)
- [x] https://github.com/ipfs/go-cid-utils Nobody seems to have anything to say on this and the repo is completely empty, with no issues or anything, so maybe we should just delete it.

**Things that might be dead, but need clarity from their owners/maintainers:**

- [ ] https://github.com/ipfs/astralboot
- [ ] https://github.com/ipfs/bitswap-ml Shutting down and merging with research-bitswap? Readme/description pretty opaque. Deprecated according to @whyrusleeping
- [ ] https://github.com/ipfs/dataviz
- [ ] https://github.com/ipfs/fs-stress-test
- [ ] https://github.com/ipfs/go-iprs
- [ ] https://github.com/ipfs/refs
- [ ] https://github.com/ipfs/refs-denylists-dmca
- [ ] https://github.com/ipfs/file-browser
- [ ] https://github.com/ipfs/install-go-ipfs
- [ ] https://github.com/ipfs/scala-ipfs-api
- [ ] https://github.com/ipfs/apps Only one issue has discussion in the past 6 months and this issue: https://github.com/ipfs/apps/issues/37 suggests the discussions here should be happening in other places instead
- [x] https://github.com/ipfs/golang-build Not used according to @VictorBjelkholm
- [ ] https://github.com/ipfs/refs-solarnet-storage
- [ ] https://github.com/ipfs/project-repos Several folks didn’t even know the site this powers existed
- [ ] https://github.com/ipfs/POST
- [ ] https://github.com/ipfs/ops-requests
- [ ] https://github.com/ipfs/go-dnslink
- [ ] https://github.com/ipfs/connections-globe (Not used in WebUI, which has its own version)
- [ ] https://github.com/ipfs/paperhub
- [ ] https://github.com/ipfs/go-key Not used according to @whyrusleeping
- [ ] https://github.com/ipfs/go-ipfs-gateway
- [ ] https://github.com/ipfs/2016-Q3-Workshop
- [ ] https://github.com/ipfs/js-idb-pull-blob-store Only used by js-ipfs-merkle-dag, which is deprecated
- [ ] https://github.com/ipfs/go-ds-redis
- [ ] https://github.com/ipfs/go-ds-lru
- [ ] https://github.com/ipfs/ipfs-pages
- [ ] https://github.com/ipfs/websiter
- [ ] https://github.com/ipfs/js-level-pull-blob-store
- [ ] https://github.com/ipfs/go-ds-s3
- [ ] https://github.com/ipfs/test-lab Open issue on converging with other test tools: https://github.com/ipfs/test-lab/issues/28
- [ ] https://github.com/ipfs/research-bitswap Dead according to @whyrusleeping
- [ ] https://github.com/ipfs/ipfs-netjournal 
- [ ] https://github.com/ipfs/contributors-hex-grid
- [ ] https://github.com/ipfs/contributors
- [ ] https://github.com/ipfs/ipfs-nodeschool
- [ ] https://github.com/ipfs/jest-environment-aegir
- [ ] https://github.com/ipfs/glossary (Issue: https://github.com/ipfs/glossary/issues/1#issuecomment-413631173)
- [x] https://github.com/ipfs/go-ipfs-path (*deleted* since it was never actually in use)
- [x] https://github.com/ipfs/go-ipfs-path-resolver (*deleted* since it was never actually in use)
- [x] https://github.com/ipfs/go-ipfs-blockservice (*deleted* since it was never actually in use)

**Already archived, but missing standard notices:** (How much do we care to update?)

- [ ] https://github.com/ipfs/ipfs-web-app
- [ ] https://github.com/ipfs/go-ipld
- [ ] https://github.com/ipfs/js-libp2p-ipfs-nodejs
- [ ] https://github.com/ipfs/js-libp2p-ipfs-browser
- [ ] https://github.com/ipfs/ipfs.js
- [ ] https://github.com/ipfs/browserify-zlib-next
- [ ] https://github.com/ipfs/js-docker-base
- [ ] https://github.com/ipfs/node-github-issue-bot
- [ ] https://github.com/ipfs/dweblink-infra

**Turned out not to be dead:**

- ~https://github.com/ipfs/js.ipfs.io~ (2018-06-04 Per @diasdavid, this now has active work)
- ~https://github.com/ipfs/ipfs-hubot~ (Magically risen from the dead once someone pointed it out)

**Comment by Mr0grog** [comment]
We should also probably consider something similar for repos that are not really usable yet, but currently just works in progress.

**Comment by ZenGround0** [comment]
Really like those three final bullets explaining the context behind deprecation.

**Comment by whyrusleeping** [comment]
Yeah, agree with @ZenGround0. Plan sounds good to me.

**Comment by VictorBjelkholm** [comment]
Sounds good to me as well, but I would add that we make the repository archived/read-only if it's deprecated as well. This can be done in the "Options" of a repository, under "Danger Zone" > "Archive this repository "

**Comment by Mr0grog** [comment]
OK, I think we need to move forward with this. I’ll bring this up for last call feedback in next week’s all hands (2018-04-30). In the mean time, I think what we’ve locked down on here is:

- Add the topic `deprecated` to the repo (pulling this over from #57)
- Prefix the repo’s description with “DEPRECATED:”
- Prefix the README title with “DEPRECATED:” (If a repo does not have a readme or its readme is empty, add one with the title: “DEPRECATED: [repo name]”
- Follow the README title with a paragraph describing:
    - Why it was deprecated
    - When it was deprecated
    - Where to go for the same resource/functionality/whatever now (if applicable)
- Finally, if a repo is *dead*, archive it (but don’t *delete* it). A *dead* repo might be [`ipfs.js`](https://github.com/ipfs/ipfs.js), while a non-dead, non-archived one might be [`newsletter`](https://github.com/ipfs/newsletter), where we might bring it back in the future.
    - Why archive? links still work, but this hides it from most views and lists on GitHub, *drastically* reducing noise and confusion. For repos like [`support`](https://github.com/ipfs/support/issues), this also prevents people from posting new issues.
    - Downsides: issues and discussions get frozen. We may want to preserve that functionality on some repos (e.g. ones that are freshly deprecated or that haven’t gained any traction/that we can’t support, but that we might want to revisit later).

@jbenet I would really appreciate your feedback here, especially on the last point about archiving. I know you’ve had some particular concerns on that.

Again, I’ll make a last call for comments here in next week’s all hands. Barring any major concerns, let’s aim to have this decided by the end of next Thursday (2018-05-03) and use this space for tracking updates to all the relevant repos.

**Comment by whyrusleeping** [comment]
@Mr0grog this all sounds good to me. The point on downsides of archiving repos, i think we can take some of these case by case if it looks like theres still ongoing discussion. But otherwise, archiving them should help shift discussion to more constructive places (i.e. maintained repos)

**Comment by flyingzumwalt** [comment]
@mgoelzer could you help with this cleanup effort?

**Comment by mgoelzer** [comment]
Not a perfect proxy for deprecation, but below is a quick list of active repo (not archived, not marked "deprecated") with no activity before the the indicated date.  Are any of these obvious candidates for deprecation?

**Last updated Sept 2017**
https://github.com/ipfs/go-poll-endpoint
https://github.com/ipfs/research-p2p-video
https://github.com/ipfs/jest-environment-aegir
https://github.com/ipfs/js-docker-base
https://github.com/ipfs/fs-repo-migrations


**Last updated August 2017**
https://github.com/ipfs/contributors-hex-grid
https://github.com/ipfs/go-ipld-btc
https://github.com/ipfs/artwork
https://github.com/ipfs/contributors
https://github.com/ipfs/go-cid-utils

**Last updated July 2017**
https://github.com/ipfs/ipfs-nodeschool
https://github.com/ipfs/scala-ipfs-api
https://github.com/ipfs/support

**Last updated Q2 2017**
https://github.com/ipfs/dht-node
https://github.com/ipfs/get-gh-contributors
https://github.com/ipfs/webrtcsupport
https://github.com/ipfs/ipfs-pages
https://github.com/ipfs/ipfs-netjournal
https://github.com/ipfs/datatogether
https://github.com/ipfs/go-ipld-zcash


**Last updated Q1 2017**
https://github.com/ipfs/project-repos
https://github.com/ipfs/newsletter
https://github.com/ipfs/go-ds-s3
https://github.com/ipfs/archive-format
https://github.com/ipfs/apps
https://github.com/ipfs/interface-pull-blob-store
https://github.com/ipfs/research-blockchain-data
https://github.com/ipfs/websiter
https://github.com/ipfs/file-browser

**Last updated 2016 and earlier**
https://github.com/ipfs/go-key
https://github.com/ipfs/install-go-ipfs
https://github.com/ipfs/go-todocounter
https://github.com/ipfs/golang-build (fork of golang/build)
https://github.com/ipfs/astralboot
https://github.com/ipfs/go-iprs
https://github.com/ipfs/paperhub
https://github.com/ipfs/ipfs.js
https://github.com/ipfs/go-metrics-interface
https://github.com/ipfs/go-ds-lru
https://github.com/ipfs/go-ds-redis
https://github.com/ipfs/2016-Q3-Workshop
https://github.com/ipfs/ops-requests
https://github.com/ipfs/refs-solarnet-storage
https://github.com/ipfs/refs-denylists-dmca
https://github.com/ipfs/refs
https://github.com/ipfs/ipfs-mans
https://github.com/ipfs/logo
https://github.com/ipfs/dataviz
https://github.com/ipfs/bitswap-ml
https://github.com/ipfs/fs-stress-test
https://github.com/ipfs/dnslink-deploy
https://github.com/ipfs/connections-globe
https://github.com/ipfs/POST
https://github.com/ipfs/go-ipfs-gateway

**Comment by Mr0grog** [comment]
@mgoelzer have you seen this spreadsheet? https://docs.google.com/spreadsheets/d/1IDVAGfniyHCJLIxLc3y7K7YTOFGCtgwTVCZEojtNLlw/edit#gid=0 It provides a little more information on what is and isn’t deprecated than last-updated-date (which is *also* super helpful for all the orange rows, which are "unclear status").

**Comment by mgoelzer** [comment]
@Mr0grog Thanks - I had not seen the spreadsheet.  It's much more useful imo.

I'm happy to do the work of deprecating repos (per [the process you proposed](https://github.com/ipfs/docs/issues/54#issuecomment-384107777)), but need help knowing which repos should definitely be deprecated, which should be debated, etc.

**Comment by Mr0grog** [comment]
Great! @flyingzumwalt had suggesting making a last call for comments on the proposed process at Monday’s all hands, so I was holding off on discussing *which* repos to apply that to — I assume some will be contentious and it would be hard to sort out that discussion from any comments on the process.

That said, we could definitely normalize the labeling on the repos that are already somehow marked as deprecated (gray rows in the sheet):

- https://github.com/ipfs/ipfs-hubot
- https://github.com/ipfs/starlog
- https://github.com/ipfs/examples
- https://github.com/ipfs/faq
- https://github.com/ipfs/http-api-spec
- https://github.com/ipfs/go-blocks
- https://github.com/ipfs/ipfs-web-app
- https://github.com/ipfs/go-ipld
- https://github.com/ipfs/go-commands
- https://github.com/ipfs/js-ipfs-merkle-dag
- https://github.com/ipfs/support
- https://github.com/ipfs/js-libp2p-ipfs-nodejs
- https://github.com/ipfs/js-libp2p-ipfs-browser

And the ones that are supremely obvious or that folks have already stated are dead on Slack & IRC:

- https://github.com/ipfs/ipfs.js
- https://github.com/ipfs/newsletter
- https://github.com/ipfs/datatogether
- https://github.com/ipfs/ipfs-mans

**Comment by Mr0grog** [comment]
OK, there’s been no other feedback, so I think we are good with the rules laid out above in https://github.com/ipfs/docs/issues/54#issuecomment-384107777 .

@mgoelzer I don’t have the rights to modify topics/descriptions/archived status anywhere, so if you’ve got the time and interest to help on updating things, that’d be incredibly wonderful.

**Definitely deprecated repos:**

- [ ] https://github.com/ipfs/ipfs-hubot
- [ ] https://github.com/ipfs/starlog
- [ ] https://github.com/ipfs/examples
- [ ] https://github.com/ipfs/faq
- [ ] https://github.com/ipfs/http-api-spec
- [ ] https://github.com/ipfs/go-blocks
- [ ] https://github.com/ipfs/ipfs-web-app
- [ ] https://github.com/ipfs/go-ipld
- [ ] https://github.com/ipfs/go-commands
- [ ] https://github.com/ipfs/js-ipfs-merkle-dag
- [ ] https://github.com/ipfs/support
- [ ] https://github.com/ipfs/js-libp2p-ipfs-nodejs
- [ ] https://github.com/ipfs/js-libp2p-ipfs-browser
- [ ] https://github.com/ipfs/ipfs.js
- [ ] https://github.com/ipfs/newsletter
- [ ] https://github.com/ipfs/datatogether
- [ ] https://github.com/ipfs/ipfs-mans
- [ ] https://github.com/ipfs/dnslink-deploy Dead according to @VictorBjelkholm
- [ ] https://github.com/ipfs/browserify-zlib-next
- [ ] https://github.com/ipfs/js-docker-base

**Things that need clarity from their owners/maintainers:**

- [ ] https://github.com/ipfs/astralboot
- [ ] https://github.com/ipfs/bitswap-ml Shutting down and merging with research-bitswap? Readme/description pretty opaque. Deprecated according to @whyrusleeping
- [ ] https://github.com/ipfs/dataviz
- [ ] https://github.com/ipfs/fs-stress-test
- [ ] https://github.com/ipfs/go-iprs
- [ ] https://github.com/ipfs/refs
- [ ] https://github.com/ipfs/refs-denylists-dmca
- [ ] https://github.com/ipfs/file-browser
- [ ] https://github.com/ipfs/install-go-ipfs
- [ ] https://github.com/ipfs/scala-ipfs-api
- [ ] https://github.com/ipfs/apps Only one issue has discussion in the past 6 months and this issue: https://github.com/ipfs/apps/issues/37 suggests the discussions here should be happening in other places instead
- [ ] https://github.com/ipfs/golang-build Not used according to @VictorBjelkholm
- [ ] https://github.com/ipfs/refs-solarnet-storage
- [ ] https://github.com/ipfs/project-repos Several folks didn’t even know the site this powers existed
- [ ] https://github.com/ipfs/POST
- [ ] https://github.com/ipfs/ops-requests
- [ ] https://github.com/ipfs/go-dnslink
- [ ] https://github.com/ipfs/connections-globe (Not used in WebUI, which has its own version)
- [ ] https://github.com/ipfs/paperhub
- [ ] https://github.com/ipfs/go-key Not used according to @whyrusleeping
- [ ] https://github.com/ipfs/go-ipfs-gateway
- [ ] https://github.com/ipfs/go-metrics-interface
- [ ] https://github.com/ipfs/2016-Q3-Workshop
- [ ] https://github.com/ipfs/go-metrics-prometheus Looks like possibly still used? (Has a semi-recent update) Unclear if it needs some README love or if dead.
- [ ] https://github.com/ipfs/js-idb-pull-blob-store Only used by js-ipfs-merkle-dag, which is deprecated
- [ ] https://github.com/ipfs/go-ds-redis
- [ ] https://github.com/ipfs/go-ds-lru
- [ ] https://github.com/ipfs/ipfs-pages
- [ ] https://github.com/ipfs/websiter
- [ ] https://github.com/ipfs/js-level-pull-blob-store
- [ ] https://github.com/ipfs/go-ds-s3
- [ ] https://github.com/ipfs/test-lab Open issue on converging with other test tools: https://github.com/ipfs/test-lab/issues/28
- [ ] https://github.com/ipfs/research-bitswap Dead according to @whyrusleeping
- [ ] https://github.com/ipfs/go-sbs
- [ ] https://github.com/ipfs/ipfs-netjournal 
- [ ] https://github.com/ipfs/contributors-hex-grid
- [ ] https://github.com/ipfs/contributors
- [ ] https://github.com/ipfs/ipfs-nodeschool
- [ ] https://github.com/ipfs/go-cid-utils Since this is completely empty, maybe we should just delete it?
- [ ] https://github.com/ipfs/jest-environment-aegir
- [ ] https://github.com/ipfs/js.ipfs.io

**Comment by Mr0grog** [comment]
@Kubuxu Great, I’ve removed it from the list and added it to #55. Should I do the same with go-metrics-interface?

Would you please either: make sure both of those have a README that at least has a one-paragraph description or post a quick 1-2 sentence description of each in #55 and I’ll help turn those into PRs?

**Comment by Kubuxu** [comment]
Same with go-metrics-interface. Will do.

**Comment by kevina** [comment]
https://github.com/ipfs/go-ipfs-blockservice/ now removed by @Stebalien.

**Comment by Mr0grog** [comment]
Update here: we have a way we want to mark things and a list of repos that probably need those markings (see top of this thread). What this needs is individuals to:

- Check listed repos to make sure they still really appear to be deprecated.
- If so, submit an issue or PR as appropriate:
    - PR to update the README to explain the repo is deprecated and say why.
    - Issue to request a repo admin update the description, update the tags, and archive the repo.
    - Post back here with the issue/PR number so we can put it in the checklist to monitor it.
    - If you are a repo admin, please go ahead and just do the above things!

Anybody who’s got some free time, just pick one repo from the list that’s not checked off and do the above! It would be enormously helpful.

**Comment by jessicaschilling** [comment]
Support on this didn't follow through, and initial effort is now outdated. Closing.
