### ISSUE TITLE
GitHub Hygiene: Make sure every repo has a description and readme

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#55]
Developers who are building things on top of IPFS have pretty much all indicated that they’ve solved a lot of their problems by digging through IPFS source code and through the repos here on GitHub. We won’t have perfect docs for them tomorrow, but one quick and easy thing we can do is make sure every repo has a description. A lot of them don’t:

**IPFS**

- [ ] https://github.com/ipfs/js-datastore-core Issue: ipfs/js-datastore-core#11
- [x] https://github.com/ipfs/go-ipfs-cmdkit Issue: ipfs/go-ipfs-cmdkit#20
- [x] https://github.com/ipfs/go-ds-badger Issue: ipfs/go-ds-badger#16
- [ ] https://github.com/ipfs/go-block-format Issue: ipfs/go-block-format#10
- [x] https://github.com/ipfs/ipfs-ds-convert Issue: ipfs/ipfs-ds-convert#10
- [x] https://github.com/ipfs/ci-sync Issue: ipfs/ci-sync#10
- [ ] https://github.com/ipfs/kubernetes-ipfs Issue: ipfs/kubernetes-ipfs#50
- [x] https://github.com/ipfs/jenkins-libs Issue: ipfs/jenkins-libs#8
- [ ] https://github.com/ipfs/go-sbs (No readme) Needs deprecation (see https://github.com/ipfs/docs/issues/54#issuecomment-386409096).
- [x] ~https://github.com/ipfs/go-cid-utils (Completely empty repo)~ This was deleted.
- [x] https://github.com/ipfs/ipld-unixfs (Empty readme) PR: https://github.com/ipfs/ipld-unixfs/pull/8
- [x] https://github.com/ipfs/go-ipfs-archived (Empty readme) Issue: ipfs/go-ipfs-archived#1
- [ ] https://github.com/ipfs/go-metrics-prometheus (No readme) Issue: ipfs/go-metrics-prometheus#2
- [ ] https://github.com/ipfs/go-metrics-interface (No readme or description) Issue: ipfs/go-metrics-interface#1
- [x] https://github.com/ipfs/go-ipns Issue: ipfs/go-ipns#7
- [ ] https://github.com/ipfs/go-ipfs-config Issue: ipfs/go-ipfs-config#1

**Libp2p**

- [ ] https://github.com/libp2p/pubsub-notes
- [ ] https://github.com/libp2p/go-xtp
- [ ] https://github.com/libp2p/go-libp2p-interface-pnet
- [ ] https://github.com/libp2p/go-libp2p-pnet
- [ ] https://github.com/libp2p/go-libp2p-dummy-conn
- [ ] https://github.com/libp2p/js-libp2p-record
- [ ] https://github.com/libp2p/js-libp2p-crypto-secp256k1
- [ ] https://github.com/libp2p/js-libp2p-circuit
- [ ] https://github.com/libp2p/go-libp2p-identify
- [ ] https://github.com/libp2p/go-flow-metrics
- [ ] https://github.com/libp2p/go-buffer-pool
- [ ] https://github.com/libp2p/go-conn-security
- [ ] https://github.com/libp2p/go-conn-security-multistream
- [ ] https://github.com/libp2p/go-reuseport-transport
- [ ] https://github.com/libp2p/go-libp2p-transport-upgrader

**IPLD**

- [ ] https://github.com/ipld/ipld-examples
- [ ] https://github.com/ipld/js-ipld-eth-tx
- [ ] https://github.com/ipld/js-ipld-eth-trie
- [ ] https://github.com/ipld/js-ipld-eth-account-snapshot
- [ ] https://github.com/ipld/js-ipld-eth-block-list
- [ ] https://github.com/ipld/js-ipld-eth-storage-trie
- [ ] https://github.com/ipld/js-ipld-eth-tx-trie
- [ ] https://github.com/ipld/js-ipld-selector
- [ ] https://github.com/ipld/js-ipld-git
- [ ] https://github.com/ipld/ipld-yang
- [ ] https://github.com/ipld/go-ipld-daghelpers

**Comment by Mr0grog** [comment]
Tagging @mgoelzer if you want to take ownership over the Libp2p side of this list (or move it to the libp2p org).

**Comment by jessicaschilling** [comment]
This is an old issue, and we'll need to regenerate the list of repos, but it's still a valid effort.

**Comment by jessicaschilling** [comment]
Support on this didn't follow through, and initial effort is now outdated. Closing.
