### ISSUE TITLE
Audit & integrate old examples

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#76]
Examples from the previous docs site still link to the “examples viewer” JS app in the old site. We should integrate them into this site directly. The example viewer is neat, but it’s another thing to maintain, and these examples should *probably* be normal pages/directories here. *(Disagree? Post here and let us know!)*

We **also** need to audit these examples for relevancy and accuracy. A lot of them might be out of date.

**Comment by Mr0grog** [comment]
#115 partially addresses this by moving the old examples here instead of linking to the old docs site. All these examples are still old and still need to be audited for relevancy and accuracy. Some should also be classified as guides instead of examples or be merged into one of the concept docs.

- [ ] [Making Your Own IPFS Service](https://github.com/ipfs/docs/tree/51a1f2ac3ca89dd1de71249eefcfc6203d8fd641/content/guides/examples/api/service)
- [ ] [Visualizing Objects with Graphmd](https://github.com/ipfs/docs/blob/51a1f2ac3ca89dd1de71249eefcfc6203d8fd641/content/guides/examples/graphmd/index.md)
- [ ] [Dealing with Blocks](https://github.com/ipfs/docs/blob/51a1f2ac3ca89dd1de71249eefcfc6203d8fd641/content/guides/examples/blocks.md)
- [ ] [Modifying the bootstrap peers list](https://github.com/ipfs/docs/blob/51a1f2ac3ca89dd1de71249eefcfc6203d8fd641/content/guides/examples/bootstrap.md)
- [ ] [Configuring Your Node](https://github.com/ipfs/docs/blob/51a1f2ac3ca89dd1de71249eefcfc6203d8fd641/content/guides/examples/config.md)
- [ ] [Git, Even More Distributed](https://github.com/ipfs/docs/blob/51a1f2ac3ca89dd1de71249eefcfc6203d8fd641/content/guides/examples/git.md)
- [ ] [The Inter-Planetary Naming System](https://github.com/ipfs/docs/blob/51a1f2ac3ca89dd1de71249eefcfc6203d8fd641/content/guides/examples/ipns.md)
- [ ] [Playing with the Network](https://github.com/ipfs/docs/blob/51a1f2ac3ca89dd1de71249eefcfc6203d8fd641/content/guides/examples/network.md)
- [ ] [Pinning Files](https://github.com/ipfs/docs/blob/51a1f2ac3ca89dd1de71249eefcfc6203d8fd641/content/guides/examples/pinning.md)
- [ ] [Snapshots](https://github.com/ipfs/docs/blob/51a1f2ac3ca89dd1de71249eefcfc6203d8fd641/content/guides/examples/snapshots.md)
- [ ] [Playing Videos](https://github.com/ipfs/docs/blob/51a1f2ac3ca89dd1de71249eefcfc6203d8fd641/content/guides/examples/videos.md)
- [ ] [IPFS for Websites](https://github.com/ipfs/docs/blob/51a1f2ac3ca89dd1de71249eefcfc6203d8fd641/content/guides/examples/websites.md)

**Comment by jessicaschilling** [comment]
Closing this issue, since it rolls into our larger overall content audit (#178) and revamp of the docs platform as a whole (#179, #180).
